version: '3.8'
services:
  dev-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    ports:
      - 5434:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - freecodecamp
networks:
  freecodecamp:
